### ISSUE TITLE
On new game error produced when opening inventory.

### ISSUE THREAD

**Issue by johnsaucier** [appuns/DSPBigInventory#2]
This error only seems to happen in a new game. It doesn't matter if its loaded with other mods, or its the only mod loaded.

```
[Unity] System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at UIStorageGrid._OnUpdate () [0x0016f] in <b7caf566f9724ba098c7ba3ac82390b0>:0 
  at ManualBehaviour._Update () [0x0001f] in <b7caf566f9724ba098c7ba3ac82390b0>:0 
[Unity] System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at UIStorageGrid._OnUpdate () [0x0016f] in <b7caf566f9724ba098c7ba3ac82390b0>:0 
  at ManualBehaviour._Update () [0x0001f] in <b7caf566f9724ba098c7ba3ac82390b0>:0 
[Unity] System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at UIStorageGrid._OnUpdate () [0x0016f] in <b7caf566f9724ba098c7ba3ac82390b0>:0 
  at ManualBehaviour._Update () [0x0001f] in <b7caf566f9724ba098c7ba3ac82390b0>:0
``` 
  
I made sure to disable all mods and began going through each one to track down which mod was causing the error. And traced it back to DSPBigInventory. It happens every single time without fail. Sometimes I have to open the inventory then the mecha inventory, sometimes just the inventory, both cause the error to appear.

I then disabled DSPBigInventory, and re-enabled all other mods I was using. I created a new game, and did not get the error. I was able to play long enough to get quite a few things researched and an inventory loaded with stuff. I then saved it, exited, re-enabled DSPBiginventory and started the game again.

The error did not appear when I opened the inventory, which leads me to believe that it only happens in a new game when you open the inventory for the first time. To test my theory, I then exited the game, started a new one and it produced the error again when the inventory was opened for the first time.

**Comment by appuns** [comment]
Thanks for the info!
I fixed and released.
Check it.

**Comment by johnsaucier** [comment]
The issue appears to be gone, so its fixed. I'll go ahead and close this now.
Thanks again.
